/********************************************************************************
** Form generated from reading UI file 'measure_dialog.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MEASURE_DIALOG_H
#define UI_MEASURE_DIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QPushButton>
#include <QtGui/QScrollArea>
#include <QtGui/QSpacerItem>
#include <QtGui/QTableWidget>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MeasureDialog
{
public:
    QVBoxLayout *verticalLayout_2;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QVBoxLayout *verticalLayout;
    QTableWidget *tableWidget;
    QHBoxLayout *horizontalLayout;
    QSpacerItem *horizontalSpacer;
    QPushButton *cancelPushButton;
    QPushButton *choosePushButton;

    void setupUi(QDialog *MeasureDialog)
    {
        if (MeasureDialog->objectName().isEmpty())
            MeasureDialog->setObjectName(QString::fromUtf8("MeasureDialog"));
        MeasureDialog->resize(564, 493);
        MeasureDialog->setFocusPolicy(Qt::NoFocus);
        verticalLayout_2 = new QVBoxLayout(MeasureDialog);
        verticalLayout_2->setSpacing(1);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(1, 1, 1, 1);
        scrollArea = new QScrollArea(MeasureDialog);
        scrollArea->setObjectName(QString::fromUtf8("scrollArea"));
        scrollArea->setFocusPolicy(Qt::NoFocus);
        scrollArea->setFrameShape(QFrame::NoFrame);
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QString::fromUtf8("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 562, 452));
        scrollAreaWidgetContents->setFocusPolicy(Qt::NoFocus);
        verticalLayout = new QVBoxLayout(scrollAreaWidgetContents);
        verticalLayout->setSpacing(1);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        tableWidget = new QTableWidget(scrollAreaWidgetContents);
        if (tableWidget->columnCount() < 2)
            tableWidget->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        if (tableWidget->rowCount() < 54)
            tableWidget->setRowCount(54);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(7, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(8, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(9, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(10, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(11, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(12, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(13, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(14, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(15, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(16, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(17, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(18, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(19, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(20, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(21, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(22, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(23, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(24, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(25, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(26, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(27, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(28, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(29, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(30, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(31, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(32, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(33, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(34, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(35, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(36, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(37, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(38, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(39, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(40, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(41, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(42, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(43, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(44, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(45, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(46, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(47, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(48, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(49, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(50, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(51, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(52, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(53, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWidget->setItem(0, 0, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableWidget->setItem(0, 1, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableWidget->setItem(1, 0, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        tableWidget->setItem(1, 1, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableWidget->setItem(2, 0, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        tableWidget->setItem(2, 1, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableWidget->setItem(3, 0, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        tableWidget->setItem(3, 1, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        tableWidget->setItem(4, 0, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        tableWidget->setItem(4, 1, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        tableWidget->setItem(5, 0, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        tableWidget->setItem(5, 1, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        tableWidget->setItem(6, 0, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        tableWidget->setItem(6, 1, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        tableWidget->setItem(7, 0, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        tableWidget->setItem(7, 1, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        tableWidget->setItem(8, 0, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        tableWidget->setItem(8, 1, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        tableWidget->setItem(9, 0, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        tableWidget->setItem(9, 1, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWidget->setItem(10, 0, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWidget->setItem(10, 1, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWidget->setItem(11, 0, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWidget->setItem(11, 1, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        tableWidget->setItem(12, 0, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWidget->setItem(12, 1, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        tableWidget->setItem(13, 0, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        tableWidget->setItem(13, 1, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        tableWidget->setItem(14, 0, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWidget->setItem(14, 1, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        tableWidget->setItem(15, 0, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWidget->setItem(15, 1, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        tableWidget->setItem(16, 0, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        tableWidget->setItem(16, 1, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        tableWidget->setItem(17, 0, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        tableWidget->setItem(17, 1, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        tableWidget->setItem(18, 0, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        tableWidget->setItem(18, 1, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        tableWidget->setItem(19, 0, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        tableWidget->setItem(19, 1, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        tableWidget->setItem(20, 0, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        tableWidget->setItem(20, 1, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        tableWidget->setItem(21, 0, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        tableWidget->setItem(21, 1, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        tableWidget->setItem(22, 0, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        tableWidget->setItem(22, 1, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        tableWidget->setItem(23, 0, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        tableWidget->setItem(23, 1, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        tableWidget->setItem(24, 0, __qtablewidgetitem103);
        QTableWidgetItem *__qtablewidgetitem104 = new QTableWidgetItem();
        tableWidget->setItem(24, 1, __qtablewidgetitem104);
        QTableWidgetItem *__qtablewidgetitem105 = new QTableWidgetItem();
        tableWidget->setItem(25, 0, __qtablewidgetitem105);
        QTableWidgetItem *__qtablewidgetitem106 = new QTableWidgetItem();
        tableWidget->setItem(25, 1, __qtablewidgetitem106);
        QTableWidgetItem *__qtablewidgetitem107 = new QTableWidgetItem();
        tableWidget->setItem(26, 0, __qtablewidgetitem107);
        QTableWidgetItem *__qtablewidgetitem108 = new QTableWidgetItem();
        tableWidget->setItem(26, 1, __qtablewidgetitem108);
        QTableWidgetItem *__qtablewidgetitem109 = new QTableWidgetItem();
        tableWidget->setItem(27, 0, __qtablewidgetitem109);
        QTableWidgetItem *__qtablewidgetitem110 = new QTableWidgetItem();
        tableWidget->setItem(27, 1, __qtablewidgetitem110);
        QTableWidgetItem *__qtablewidgetitem111 = new QTableWidgetItem();
        tableWidget->setItem(28, 0, __qtablewidgetitem111);
        QTableWidgetItem *__qtablewidgetitem112 = new QTableWidgetItem();
        tableWidget->setItem(28, 1, __qtablewidgetitem112);
        QTableWidgetItem *__qtablewidgetitem113 = new QTableWidgetItem();
        tableWidget->setItem(29, 0, __qtablewidgetitem113);
        QTableWidgetItem *__qtablewidgetitem114 = new QTableWidgetItem();
        tableWidget->setItem(29, 1, __qtablewidgetitem114);
        QTableWidgetItem *__qtablewidgetitem115 = new QTableWidgetItem();
        tableWidget->setItem(30, 0, __qtablewidgetitem115);
        QTableWidgetItem *__qtablewidgetitem116 = new QTableWidgetItem();
        tableWidget->setItem(30, 1, __qtablewidgetitem116);
        QTableWidgetItem *__qtablewidgetitem117 = new QTableWidgetItem();
        tableWidget->setItem(31, 0, __qtablewidgetitem117);
        QTableWidgetItem *__qtablewidgetitem118 = new QTableWidgetItem();
        tableWidget->setItem(31, 1, __qtablewidgetitem118);
        QTableWidgetItem *__qtablewidgetitem119 = new QTableWidgetItem();
        tableWidget->setItem(32, 0, __qtablewidgetitem119);
        QTableWidgetItem *__qtablewidgetitem120 = new QTableWidgetItem();
        tableWidget->setItem(32, 1, __qtablewidgetitem120);
        QTableWidgetItem *__qtablewidgetitem121 = new QTableWidgetItem();
        tableWidget->setItem(33, 0, __qtablewidgetitem121);
        QTableWidgetItem *__qtablewidgetitem122 = new QTableWidgetItem();
        tableWidget->setItem(33, 1, __qtablewidgetitem122);
        QTableWidgetItem *__qtablewidgetitem123 = new QTableWidgetItem();
        tableWidget->setItem(34, 0, __qtablewidgetitem123);
        QTableWidgetItem *__qtablewidgetitem124 = new QTableWidgetItem();
        tableWidget->setItem(34, 1, __qtablewidgetitem124);
        QTableWidgetItem *__qtablewidgetitem125 = new QTableWidgetItem();
        tableWidget->setItem(35, 0, __qtablewidgetitem125);
        QTableWidgetItem *__qtablewidgetitem126 = new QTableWidgetItem();
        tableWidget->setItem(35, 1, __qtablewidgetitem126);
        QTableWidgetItem *__qtablewidgetitem127 = new QTableWidgetItem();
        tableWidget->setItem(36, 0, __qtablewidgetitem127);
        QTableWidgetItem *__qtablewidgetitem128 = new QTableWidgetItem();
        tableWidget->setItem(36, 1, __qtablewidgetitem128);
        QTableWidgetItem *__qtablewidgetitem129 = new QTableWidgetItem();
        tableWidget->setItem(37, 0, __qtablewidgetitem129);
        QTableWidgetItem *__qtablewidgetitem130 = new QTableWidgetItem();
        tableWidget->setItem(37, 1, __qtablewidgetitem130);
        QTableWidgetItem *__qtablewidgetitem131 = new QTableWidgetItem();
        tableWidget->setItem(38, 0, __qtablewidgetitem131);
        QTableWidgetItem *__qtablewidgetitem132 = new QTableWidgetItem();
        tableWidget->setItem(38, 1, __qtablewidgetitem132);
        QTableWidgetItem *__qtablewidgetitem133 = new QTableWidgetItem();
        tableWidget->setItem(39, 0, __qtablewidgetitem133);
        QTableWidgetItem *__qtablewidgetitem134 = new QTableWidgetItem();
        tableWidget->setItem(39, 1, __qtablewidgetitem134);
        QTableWidgetItem *__qtablewidgetitem135 = new QTableWidgetItem();
        tableWidget->setItem(40, 0, __qtablewidgetitem135);
        QTableWidgetItem *__qtablewidgetitem136 = new QTableWidgetItem();
        tableWidget->setItem(40, 1, __qtablewidgetitem136);
        QTableWidgetItem *__qtablewidgetitem137 = new QTableWidgetItem();
        tableWidget->setItem(41, 0, __qtablewidgetitem137);
        QTableWidgetItem *__qtablewidgetitem138 = new QTableWidgetItem();
        tableWidget->setItem(41, 1, __qtablewidgetitem138);
        QTableWidgetItem *__qtablewidgetitem139 = new QTableWidgetItem();
        tableWidget->setItem(42, 0, __qtablewidgetitem139);
        QTableWidgetItem *__qtablewidgetitem140 = new QTableWidgetItem();
        tableWidget->setItem(42, 1, __qtablewidgetitem140);
        QTableWidgetItem *__qtablewidgetitem141 = new QTableWidgetItem();
        tableWidget->setItem(43, 0, __qtablewidgetitem141);
        QTableWidgetItem *__qtablewidgetitem142 = new QTableWidgetItem();
        tableWidget->setItem(43, 1, __qtablewidgetitem142);
        QTableWidgetItem *__qtablewidgetitem143 = new QTableWidgetItem();
        tableWidget->setItem(44, 0, __qtablewidgetitem143);
        QTableWidgetItem *__qtablewidgetitem144 = new QTableWidgetItem();
        tableWidget->setItem(44, 1, __qtablewidgetitem144);
        QTableWidgetItem *__qtablewidgetitem145 = new QTableWidgetItem();
        tableWidget->setItem(45, 0, __qtablewidgetitem145);
        QTableWidgetItem *__qtablewidgetitem146 = new QTableWidgetItem();
        tableWidget->setItem(45, 1, __qtablewidgetitem146);
        QTableWidgetItem *__qtablewidgetitem147 = new QTableWidgetItem();
        tableWidget->setItem(46, 0, __qtablewidgetitem147);
        QTableWidgetItem *__qtablewidgetitem148 = new QTableWidgetItem();
        tableWidget->setItem(46, 1, __qtablewidgetitem148);
        QTableWidgetItem *__qtablewidgetitem149 = new QTableWidgetItem();
        tableWidget->setItem(47, 0, __qtablewidgetitem149);
        QTableWidgetItem *__qtablewidgetitem150 = new QTableWidgetItem();
        tableWidget->setItem(47, 1, __qtablewidgetitem150);
        QTableWidgetItem *__qtablewidgetitem151 = new QTableWidgetItem();
        tableWidget->setItem(48, 0, __qtablewidgetitem151);
        QTableWidgetItem *__qtablewidgetitem152 = new QTableWidgetItem();
        tableWidget->setItem(48, 1, __qtablewidgetitem152);
        QTableWidgetItem *__qtablewidgetitem153 = new QTableWidgetItem();
        tableWidget->setItem(49, 0, __qtablewidgetitem153);
        QTableWidgetItem *__qtablewidgetitem154 = new QTableWidgetItem();
        tableWidget->setItem(49, 1, __qtablewidgetitem154);
        QTableWidgetItem *__qtablewidgetitem155 = new QTableWidgetItem();
        tableWidget->setItem(50, 0, __qtablewidgetitem155);
        QTableWidgetItem *__qtablewidgetitem156 = new QTableWidgetItem();
        tableWidget->setItem(50, 1, __qtablewidgetitem156);
        QTableWidgetItem *__qtablewidgetitem157 = new QTableWidgetItem();
        tableWidget->setItem(51, 0, __qtablewidgetitem157);
        QTableWidgetItem *__qtablewidgetitem158 = new QTableWidgetItem();
        tableWidget->setItem(51, 1, __qtablewidgetitem158);
        QTableWidgetItem *__qtablewidgetitem159 = new QTableWidgetItem();
        tableWidget->setItem(52, 0, __qtablewidgetitem159);
        QTableWidgetItem *__qtablewidgetitem160 = new QTableWidgetItem();
        tableWidget->setItem(52, 1, __qtablewidgetitem160);
        QTableWidgetItem *__qtablewidgetitem161 = new QTableWidgetItem();
        tableWidget->setItem(53, 0, __qtablewidgetitem161);
        QTableWidgetItem *__qtablewidgetitem162 = new QTableWidgetItem();
        tableWidget->setItem(53, 1, __qtablewidgetitem162);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setStyleSheet(QString::fromUtf8("QTableWidget{\n"
"	font:14pt \"Arial\";\n"
"}\n"
""));
        tableWidget->setFrameShape(QFrame::StyledPanel);
        tableWidget->setLineWidth(1);
        tableWidget->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidget->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget->setShowGrid(true);
        tableWidget->setWordWrap(true);
        tableWidget->setCornerButtonEnabled(true);
        tableWidget->setColumnCount(2);
        tableWidget->horizontalHeader()->setVisible(false);
        tableWidget->horizontalHeader()->setStretchLastSection(true);
        tableWidget->verticalHeader()->setVisible(true);
        tableWidget->verticalHeader()->setDefaultSectionSize(35);
        tableWidget->verticalHeader()->setMinimumSectionSize(30);

        verticalLayout->addWidget(tableWidget);

        scrollArea->setWidget(scrollAreaWidgetContents);

        verticalLayout_2->addWidget(scrollArea);

        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setSpacing(6);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer);

        cancelPushButton = new QPushButton(MeasureDialog);
        cancelPushButton->setObjectName(QString::fromUtf8("cancelPushButton"));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(cancelPushButton->sizePolicy().hasHeightForWidth());
        cancelPushButton->setSizePolicy(sizePolicy);
        QFont font;
        font.setFamily(QString::fromUtf8("Arial"));
        font.setPointSize(14);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        cancelPushButton->setFont(font);
        cancelPushButton->setFocusPolicy(Qt::NoFocus);
        cancelPushButton->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	font:14pt \"Arial\";\n"
"}"));

        horizontalLayout->addWidget(cancelPushButton);

        choosePushButton = new QPushButton(MeasureDialog);
        choosePushButton->setObjectName(QString::fromUtf8("choosePushButton"));
        sizePolicy.setHeightForWidth(choosePushButton->sizePolicy().hasHeightForWidth());
        choosePushButton->setSizePolicy(sizePolicy);
        choosePushButton->setFont(font);
        choosePushButton->setFocusPolicy(Qt::NoFocus);
        choosePushButton->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	font:14pt \"Arial\";\n"
"}"));

        horizontalLayout->addWidget(choosePushButton);


        verticalLayout_2->addLayout(horizontalLayout);

        verticalLayout_2->setStretch(0, 12);
        verticalLayout_2->setStretch(1, 1);

        retranslateUi(MeasureDialog);
        QObject::connect(cancelPushButton, SIGNAL(clicked()), MeasureDialog, SLOT(reject()));
        QObject::connect(choosePushButton, SIGNAL(clicked()), MeasureDialog, SLOT(accept()));

        QMetaObject::connectSlotsByName(MeasureDialog);
    } // setupUi

    void retranslateUi(QDialog *MeasureDialog)
    {
        MeasureDialog->setWindowTitle(QApplication::translate("MeasureDialog", "Dialog", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MeasureDialog", "Measurement", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem1->setText(QApplication::translate("MeasureDialog", "A%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem2->setText(QApplication::translate("MeasureDialog", "AdBa", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem3->setText(QApplication::translate("MeasureDialog", "AdBr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem4->setText(QApplication::translate("MeasureDialog", "B%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem5->setText(QApplication::translate("MeasureDialog", "BdBB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem6->setText(QApplication::translate("MeasureDialog", "BdBr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->verticalHeaderItem(6);
        ___qtablewidgetitem7->setText(QApplication::translate("MeasureDialog", "A^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->verticalHeaderItem(7);
        ___qtablewidgetitem8->setText(QApplication::translate("MeasureDialog", "B^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget->verticalHeaderItem(8);
        ___qtablewidgetitem9->setText(QApplication::translate("MeasureDialog", "I/", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget->verticalHeaderItem(9);
        ___qtablewidgetitem10->setText(QApplication::translate("MeasureDialog", "I(W)/", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget->verticalHeaderItem(10);
        ___qtablewidgetitem11->setText(QApplication::translate("MeasureDialog", "T(A^)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget->verticalHeaderItem(11);
        ___qtablewidgetitem12->setText(QApplication::translate("MeasureDialog", "ML", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget->verticalHeaderItem(12);
        ___qtablewidgetitem13->setText(QApplication::translate("MeasureDialog", "%(r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget->verticalHeaderItem(13);
        ___qtablewidgetitem14->setText(QApplication::translate("MeasureDialog", "%(m)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget->verticalHeaderItem(14);
        ___qtablewidgetitem15->setText(QApplication::translate("MeasureDialog", "%(m-r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget->verticalHeaderItem(15);
        ___qtablewidgetitem16->setText(QApplication::translate("MeasureDialog", "U(r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget->verticalHeaderItem(16);
        ___qtablewidgetitem17->setText(QApplication::translate("MeasureDialog", "U(m)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget->verticalHeaderItem(17);
        ___qtablewidgetitem18->setText(QApplication::translate("MeasureDialog", "U(m-r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget->verticalHeaderItem(18);
        ___qtablewidgetitem19->setText(QApplication::translate("MeasureDialog", "P(r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget->verticalHeaderItem(19);
        ___qtablewidgetitem20->setText(QApplication::translate("MeasureDialog", "P(m)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget->verticalHeaderItem(20);
        ___qtablewidgetitem21->setText(QApplication::translate("MeasureDialog", "P(m-r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget->verticalHeaderItem(21);
        ___qtablewidgetitem22->setText(QApplication::translate("MeasureDialog", "S(r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget->verticalHeaderItem(22);
        ___qtablewidgetitem23->setText(QApplication::translate("MeasureDialog", "S(m)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget->verticalHeaderItem(23);
        ___qtablewidgetitem24->setText(QApplication::translate("MeasureDialog", "S(m-r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget->verticalHeaderItem(24);
        ___qtablewidgetitem25->setText(QApplication::translate("MeasureDialog", "I(r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget->verticalHeaderItem(25);
        ___qtablewidgetitem26->setText(QApplication::translate("MeasureDialog", "I(m)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget->verticalHeaderItem(26);
        ___qtablewidgetitem27->setText(QApplication::translate("MeasureDialog", "I(m-r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget->verticalHeaderItem(27);
        ___qtablewidgetitem28->setText(QApplication::translate("MeasureDialog", "RA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget->verticalHeaderItem(28);
        ___qtablewidgetitem29->setText(QApplication::translate("MeasureDialog", "RB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget->verticalHeaderItem(29);
        ___qtablewidgetitem30->setText(QApplication::translate("MeasureDialog", "PA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget->verticalHeaderItem(30);
        ___qtablewidgetitem31->setText(QApplication::translate("MeasureDialog", "PB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget->verticalHeaderItem(31);
        ___qtablewidgetitem32->setText(QApplication::translate("MeasureDialog", "DA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget->verticalHeaderItem(32);
        ___qtablewidgetitem33->setText(QApplication::translate("MeasureDialog", "DB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget->verticalHeaderItem(33);
        ___qtablewidgetitem34->setText(QApplication::translate("MeasureDialog", "SA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget->verticalHeaderItem(34);
        ___qtablewidgetitem35->setText(QApplication::translate("MeasureDialog", "SB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget->verticalHeaderItem(35);
        ___qtablewidgetitem36->setText(QApplication::translate("MeasureDialog", "ViA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget->verticalHeaderItem(36);
        ___qtablewidgetitem37->setText(QApplication::translate("MeasureDialog", "ViB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget->verticalHeaderItem(37);
        ___qtablewidgetitem38->setText(QApplication::translate("MeasureDialog", "VsA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget->verticalHeaderItem(38);
        ___qtablewidgetitem39->setText(QApplication::translate("MeasureDialog", "VsB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget->verticalHeaderItem(39);
        ___qtablewidgetitem40->setText(QApplication::translate("MeasureDialog", "LA^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget->verticalHeaderItem(40);
        ___qtablewidgetitem41->setText(QApplication::translate("MeasureDialog", "LB^", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget->verticalHeaderItem(41);
        ___qtablewidgetitem42->setText(QApplication::translate("MeasureDialog", "E%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget->verticalHeaderItem(42);
        ___qtablewidgetitem43->setText(QApplication::translate("MeasureDialog", "AWS-DA", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget->verticalHeaderItem(43);
        ___qtablewidgetitem44->setText(QApplication::translate("MeasureDialog", "AWS-DB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget->verticalHeaderItem(44);
        ___qtablewidgetitem45->setText(QApplication::translate("MeasureDialog", "AWS-DC", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget->verticalHeaderItem(45);
        ___qtablewidgetitem46->setText(QApplication::translate("MeasureDialog", "AWS-DD", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget->verticalHeaderItem(46);
        ___qtablewidgetitem47->setText(QApplication::translate("MeasureDialog", "AWS-D45", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget->verticalHeaderItem(47);
        ___qtablewidgetitem48->setText(QApplication::translate("MeasureDialog", "AWS-D60", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget->verticalHeaderItem(48);
        ___qtablewidgetitem49->setText(QApplication::translate("MeasureDialog", "AWS-D70", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget->verticalHeaderItem(49);
        ___qtablewidgetitem50->setText(QApplication::translate("MeasureDialog", "AWS-DCL", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget->verticalHeaderItem(50);
        ___qtablewidgetitem51->setText(QApplication::translate("MeasureDialog", "T-D(r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget->verticalHeaderItem(51);
        ___qtablewidgetitem52->setText(QApplication::translate("MeasureDialog", "T-D(m)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget->verticalHeaderItem(52);
        ___qtablewidgetitem53->setText(QApplication::translate("MeasureDialog", "T-S(m-r)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget->verticalHeaderItem(53);
        ___qtablewidgetitem54->setText(QApplication::translate("MeasureDialog", "T-D(m-r)", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = tableWidget->isSortingEnabled();
        tableWidget->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget->item(0, 0);
        ___qtablewidgetitem55->setText(QApplication::translate("MeasureDialog", "Peak amplitude in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget->item(0, 1);
        ___qtablewidgetitem56->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget->item(1, 0);
        ___qtablewidgetitem57->setText(QApplication::translate("MeasureDialog", "Signal in gate minus gate level for gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget->item(1, 1);
        ___qtablewidgetitem58->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget->item(2, 0);
        ___qtablewidgetitem59->setText(QApplication::translate("MeasureDialog", "Difference between signal and reference in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget->item(2, 1);
        ___qtablewidgetitem60->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget->item(3, 0);
        ___qtablewidgetitem61->setText(QApplication::translate("MeasureDialog", "Peak amplitude in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget->item(3, 1);
        ___qtablewidgetitem62->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget->item(4, 0);
        ___qtablewidgetitem63->setText(QApplication::translate("MeasureDialog", "Signal in gate minus gate level for gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget->item(4, 1);
        ___qtablewidgetitem64->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget->item(5, 0);
        ___qtablewidgetitem65->setText(QApplication::translate("MeasureDialog", "Difference between signal and reference in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget->item(5, 1);
        ___qtablewidgetitem66->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget->item(6, 0);
        ___qtablewidgetitem67->setText(QApplication::translate("MeasureDialog", "Position in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget->item(6, 1);
        ___qtablewidgetitem68->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget->item(7, 0);
        ___qtablewidgetitem69->setText(QApplication::translate("MeasureDialog", "Position in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget->item(7, 1);
        ___qtablewidgetitem70->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget->item(8, 0);
        ___qtablewidgetitem71->setText(QApplication::translate("MeasureDialog", "Position in gate I", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget->item(8, 1);
        ___qtablewidgetitem72->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget->item(9, 0);
        ___qtablewidgetitem73->setText(QApplication::translate("MeasureDialog", "Position in gate I in water", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget->item(9, 1);
        ___qtablewidgetitem74->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget->item(10, 0);
        ___qtablewidgetitem75->setText(QApplication::translate("MeasureDialog", "Thickness", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget->item(10, 1);
        ___qtablewidgetitem76->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget->item(11, 0);
        ___qtablewidgetitem77->setText(QApplication::translate("MeasureDialog", "Percentage of Material loss", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem78 = tableWidget->item(11, 1);
        ___qtablewidgetitem78->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem79 = tableWidget->item(12, 0);
        ___qtablewidgetitem79->setText(QApplication::translate("MeasureDialog", "Amplitude value for reference cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem80 = tableWidget->item(12, 1);
        ___qtablewidgetitem80->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem81 = tableWidget->item(13, 0);
        ___qtablewidgetitem81->setText(QApplication::translate("MeasureDialog", "Amplitude value of the measurement cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem82 = tableWidget->item(13, 1);
        ___qtablewidgetitem82->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem83 = tableWidget->item(14, 0);
        ___qtablewidgetitem83->setText(QApplication::translate("MeasureDialog", "Amplitude (measurement cursor - reference cursor)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem84 = tableWidget->item(14, 1);
        ___qtablewidgetitem84->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem85 = tableWidget->item(15, 0);
        ___qtablewidgetitem85->setText(QApplication::translate("MeasureDialog", "Ultrasonic position of the reference cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem86 = tableWidget->item(15, 1);
        ___qtablewidgetitem86->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem87 = tableWidget->item(16, 0);
        ___qtablewidgetitem87->setText(QApplication::translate("MeasureDialog", "Ultrasonic position of the measurement cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem88 = tableWidget->item(16, 1);
        ___qtablewidgetitem88->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem89 = tableWidget->item(17, 0);
        ___qtablewidgetitem89->setText(QApplication::translate("MeasureDialog", "Ultrasonic axix(measurement cursor - reference cursor)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem90 = tableWidget->item(17, 1);
        ___qtablewidgetitem90->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem91 = tableWidget->item(18, 0);
        ___qtablewidgetitem91->setText(QApplication::translate("MeasureDialog", "Probe position of the reference cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem92 = tableWidget->item(18, 1);
        ___qtablewidgetitem92->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem93 = tableWidget->item(19, 0);
        ___qtablewidgetitem93->setText(QApplication::translate("MeasureDialog", "Probe position of the measurement cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem94 = tableWidget->item(19, 1);
        ___qtablewidgetitem94->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem95 = tableWidget->item(20, 0);
        ___qtablewidgetitem95->setText(QApplication::translate("MeasureDialog", "Probe (measurement cursor - reference cursor)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem96 = tableWidget->item(20, 1);
        ___qtablewidgetitem96->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem97 = tableWidget->item(21, 0);
        ___qtablewidgetitem97->setText(QApplication::translate("MeasureDialog", "Scan position of the reference cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem98 = tableWidget->item(21, 1);
        ___qtablewidgetitem98->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem99 = tableWidget->item(22, 0);
        ___qtablewidgetitem99->setText(QApplication::translate("MeasureDialog", "Scan position of the measurment cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem100 = tableWidget->item(22, 1);
        ___qtablewidgetitem100->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem101 = tableWidget->item(23, 0);
        ___qtablewidgetitem101->setText(QApplication::translate("MeasureDialog", "Scan (measurement cursor - reference cursor)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem102 = tableWidget->item(23, 1);
        ___qtablewidgetitem102->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem103 = tableWidget->item(24, 0);
        ___qtablewidgetitem103->setText(QApplication::translate("MeasureDialog", "Index position of the reference cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem104 = tableWidget->item(24, 1);
        ___qtablewidgetitem104->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem105 = tableWidget->item(25, 0);
        ___qtablewidgetitem105->setText(QApplication::translate("MeasureDialog", "Index position of the measurement cursor", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem106 = tableWidget->item(25, 1);
        ___qtablewidgetitem106->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem107 = tableWidget->item(26, 0);
        ___qtablewidgetitem107->setText(QApplication::translate("MeasureDialog", "Index axis(measurement cursor - reference cursor)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem108 = tableWidget->item(26, 1);
        ___qtablewidgetitem108->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem109 = tableWidget->item(27, 0);
        ___qtablewidgetitem109->setText(QApplication::translate("MeasureDialog", "Reference point to the indication in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem110 = tableWidget->item(27, 1);
        ___qtablewidgetitem110->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem111 = tableWidget->item(28, 0);
        ___qtablewidgetitem111->setText(QApplication::translate("MeasureDialog", "Reference point to the indication in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem112 = tableWidget->item(28, 1);
        ___qtablewidgetitem112->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem113 = tableWidget->item(29, 0);
        ___qtablewidgetitem113->setText(QApplication::translate("MeasureDialog", "Probe front face to the indication in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem114 = tableWidget->item(29, 1);
        ___qtablewidgetitem114->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem115 = tableWidget->item(30, 0);
        ___qtablewidgetitem115->setText(QApplication::translate("MeasureDialog", "Probe front face to the indication in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem116 = tableWidget->item(30, 1);
        ___qtablewidgetitem116->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem117 = tableWidget->item(31, 0);
        ___qtablewidgetitem117->setText(QApplication::translate("MeasureDialog", "Depth of the indication in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem118 = tableWidget->item(31, 1);
        ___qtablewidgetitem118->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem119 = tableWidget->item(32, 0);
        ___qtablewidgetitem119->setText(QApplication::translate("MeasureDialog", "Depth of the indication in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem120 = tableWidget->item(32, 1);
        ___qtablewidgetitem120->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem121 = tableWidget->item(33, 0);
        ___qtablewidgetitem121->setText(QApplication::translate("MeasureDialog", "Sound path of the indication in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem122 = tableWidget->item(33, 1);
        ___qtablewidgetitem122->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem123 = tableWidget->item(34, 0);
        ___qtablewidgetitem123->setText(QApplication::translate("MeasureDialog", "Sound path of the indication in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem124 = tableWidget->item(34, 1);
        ___qtablewidgetitem124->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem125 = tableWidget->item(35, 0);
        ___qtablewidgetitem125->setText(QApplication::translate("MeasureDialog", "Volumetric position in gate A on the index axis", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem126 = tableWidget->item(35, 1);
        ___qtablewidgetitem126->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem127 = tableWidget->item(36, 0);
        ___qtablewidgetitem127->setText(QApplication::translate("MeasureDialog", "Volumetric position in gate B on the index axis", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem128 = tableWidget->item(36, 1);
        ___qtablewidgetitem128->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem129 = tableWidget->item(37, 0);
        ___qtablewidgetitem129->setText(QApplication::translate("MeasureDialog", "Volumetric position in gate A on the scan axis", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem130 = tableWidget->item(37, 1);
        ___qtablewidgetitem130->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem131 = tableWidget->item(38, 0);
        ___qtablewidgetitem131->setText(QApplication::translate("MeasureDialog", "Volumetric position in gate B on the scan axis", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem132 = tableWidget->item(38, 1);
        ___qtablewidgetitem132->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem133 = tableWidget->item(39, 0);
        ___qtablewidgetitem133->setText(QApplication::translate("MeasureDialog", "Leg(skip)of the indication in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem134 = tableWidget->item(39, 1);
        ___qtablewidgetitem134->setText(QApplication::translate("MeasureDialog", "times", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem135 = tableWidget->item(40, 0);
        ___qtablewidgetitem135->setText(QApplication::translate("MeasureDialog", "Leg(skip)of the indication in gate B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem136 = tableWidget->item(40, 1);
        ___qtablewidgetitem136->setText(QApplication::translate("MeasureDialog", "times", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem137 = tableWidget->item(41, 0);
        ___qtablewidgetitem137->setText(QApplication::translate("MeasureDialog", "Peak amplitude of the envelop in gate A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem138 = tableWidget->item(41, 1);
        ___qtablewidgetitem138->setText(QApplication::translate("MeasureDialog", "%", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem139 = tableWidget->item(42, 0);
        ___qtablewidgetitem139->setText(QApplication::translate("MeasureDialog", "Indication level for AWS-D1.5A", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem140 = tableWidget->item(42, 1);
        ___qtablewidgetitem140->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem141 = tableWidget->item(43, 0);
        ___qtablewidgetitem141->setText(QApplication::translate("MeasureDialog", "Zero reference  level for AWS-D1.5B", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem142 = tableWidget->item(43, 1);
        ___qtablewidgetitem142->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem143 = tableWidget->item(44, 0);
        ___qtablewidgetitem143->setText(QApplication::translate("MeasureDialog", "Attenuation factor for AWS-D1.5 C", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem144 = tableWidget->item(44, 1);
        ___qtablewidgetitem144->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem145 = tableWidget->item(45, 0);
        ___qtablewidgetitem145->setText(QApplication::translate("MeasureDialog", "Indication rating for AWS-D1.5D", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem146 = tableWidget->item(45, 1);
        ___qtablewidgetitem146->setText(QApplication::translate("MeasureDialog", "dB", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem147 = tableWidget->item(46, 0);
        ___qtablewidgetitem147->setText(QApplication::translate("MeasureDialog", "Discontinuity severity class for AWS-D1.5 45", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem148 = tableWidget->item(47, 0);
        ___qtablewidgetitem148->setText(QApplication::translate("MeasureDialog", "Discontinuity severity class for AWS-D1.5 60", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem149 = tableWidget->item(48, 0);
        ___qtablewidgetitem149->setText(QApplication::translate("MeasureDialog", "Discontinuity severity class for AWS-D1.5 70", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem150 = tableWidget->item(49, 0);
        ___qtablewidgetitem150->setText(QApplication::translate("MeasureDialog", "Discontinuity severity class for AWS-D1.5", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem151 = tableWidget->item(50, 0);
        ___qtablewidgetitem151->setText(QApplication::translate("MeasureDialog", "TOFD Ultrasonic Axis Reference Cursor Depth", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem152 = tableWidget->item(50, 1);
        ___qtablewidgetitem152->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem153 = tableWidget->item(51, 0);
        ___qtablewidgetitem153->setText(QApplication::translate("MeasureDialog", "TOFD Ultrasonic Axis Measure Cursor Depth", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem154 = tableWidget->item(51, 1);
        ___qtablewidgetitem154->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem155 = tableWidget->item(52, 0);
        ___qtablewidgetitem155->setText(QApplication::translate("MeasureDialog", "TOFD Scan Axis Cursor Space", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem156 = tableWidget->item(52, 1);
        ___qtablewidgetitem156->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem157 = tableWidget->item(53, 0);
        ___qtablewidgetitem157->setText(QApplication::translate("MeasureDialog", "TOFD Ultrasonic Axis Cursor Height", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem158 = tableWidget->item(53, 1);
        ___qtablewidgetitem158->setText(QApplication::translate("MeasureDialog", "mm", 0, QApplication::UnicodeUTF8));
        tableWidget->setSortingEnabled(__sortingEnabled);

        cancelPushButton->setText(QApplication::translate("MeasureDialog", "&Cancel", 0, QApplication::UnicodeUTF8));
        choosePushButton->setText(QApplication::translate("MeasureDialog", "&Choose", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MeasureDialog: public Ui_MeasureDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MEASURE_DIALOG_H
